{% set name = "ltl" %}
{% set version = "2.0.22" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://www.as.utexas.edu/~drory/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c2ec17f40b3719fd9c13b345b8101aaba4a3360f733fd259e613ebe88aabbdd4
  patches:
    - 0001_Build_shared_lib.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
  ignore_run_exports:
    # Both LAPACK and BLAS are needed during compilation for the test suite,
    # but are not actually linked against in the LTL library (they are only
    # needed in header files which are not compiled).
    # If a downstream package actually needs the LTL marray/blas.h or
    # marray/lapack.h headers, they should add libblas and / or liblapack to
    # their requirements/host section.
    - liblapack
    - libblas

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - autoconf
    - automake
    - libtool
  host:
    - libblas
    - liblapack

test:
  commands:
    # Just a simple existence test here; the build.sh script runs more tests
    # during build.
    - test -f $PREFIX/lib/libltl$SHLIB_EXT  # [unix]

about:
  home: http://www.as.utexas.edu/~drory/ltl/
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'The Little Template Library'
  description: |
    LTL provides dynamic arrays of up to 7-dimensions, subarrays and slicing,
    support for fixed-size vectors and matrices including basic linear algebra
    operations, expression templates-based evaluation, and I/O facilities for
    ascii and FITS format files. Utility classes for command-line processing
    and configuration-file processing are provided as well.
  doc_url: http://www.as.utexas.edu/~drory/ltl/doc/html/index.html

extra:
  recipe-maintainers:
    - teake
