travis:
  secure:
    BINSTAR_TOKEN: VlKO96Zeg5c8aldoFkg8AhGqecWFv9GOiDqmoPBjLjaD4awQWl6IT7FCORidJ78HitfUvy0FmLceh8VjECpGF7Psq9SS1/qEaK1nnrvljxidur0GYkHVhfS/8ABeYQadcKU48rdLoJF14swxOQzz8Y42Ci3ZSIEu2hKIAwjrr8CG4yQhwMjJBqb3hhAWN0aFqxYf7dHLPYNqGAJELVIi2wD8ATYRrw/aCr80Np233mV5zptO5bqv+Sdj+s3/PNaxlEuE1Uq/CLF6TqXmnF2oO87HYcjPQYxkwu6MwW5ZrawhBp3TWDcekO0tzGDepAYnhP+/AHGOZbkWpW2ax5G/1F2BoYfKK0bxWaJIr6ykcSWeEX5wUMszf5dhTwZmWmOV3UDoeIxggOskk0OEDVw83gcKfPSuOD/GVVRRmX6u3SmkYtYvoG2UNKmnxxARuM1kPnuS0T6RcSTn4z9gfRiKrEWexA8Q7yFzXC1xPMFhmmugoBvWqJKGpGS0cVN7Sl3QkzYXiKdwxGnE1AUUDdmPjIZtVm+8lqrVEEg2Yandu3UxhI7JKau0rb9CsmzETnQK21MHe0u7cAlL1ma2ZAi5mX6NqszlUbgNi+8wRH9GurStNbFGaKwyDD+bdChwzqwaDY8nzQ4aDBRwOsTkjsVCFMFa97cYCZ6Jt+VXTVCGgmg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
